### ISSUE TITLE
[BUG] 메인 필터 모달이 리스트 가리는 문제

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#147]
## 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.

1. 상단에 있는 이슈 아이템의 체크박스가 클릭되지 않음
2. 태그를 찍어보면 모달이 위에있어 눌리지 않음

## 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

모달의 인덱스를 조절하거나 숨기지 않게끔 수정한다.

## 참고자료
> 보여지는 뷰의 경우 스크린샷도 함께 첨부합니다.
<img width="786" alt="스크린샷 2020-11-08 오후 11 05 56" src="https://user-images.githubusercontent.com/43198553/98467107-f7fb5280-2216-11eb-8813-e48e8689f316.png">

**Comment by Taeg92** [comment]
확인했습니다!
