### ISSUE TITLE
[NEED CHECK] 시퀄라이즈 valid 체크

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#15]
## 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.

reaction model을 알맞게 생성한 것인지 확인하기
데이터 생성하면서 확인해주세용

## 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

- [x] ERD대로 reaction 테이블에 문제가 없어야 한다.

## 참고자료
> 보여지는 뷰의 경우 스크린샷도 함께 첨부합니다.
<img width="627" alt="스크린샷 2020-10-27 오후 5 59 00" src="https://user-images.githubusercontent.com/43198553/97279243-19a32400-187e-11eb-87dc-b34652e9e4d9.png">

**Comment by Park-SooYeon** [comment]
이런 스키마를 사용해도되는지 좀더 생각해보고 고민해봐야겠네요ㅠㅜ

**Comment by Park-SooYeon** [comment]
하나의 comment에 reaction이 등록되었을 때,
해당 reaction을 해준 user의 name이 무엇인지만 표시해주고, 또 리액션한 유저의 또 다른 정보(ex. reaction을 한 유저의 이미지 등)들은 나타나지 않아도 되므로 user 테이블과 관계를 가지지 않고 username만 저장해도 충분히 해당 기능을 구현할 수 있을 것 같다는 생각이 들었습니다.
Reaction | Info
-- | --
commentId | FK
emoticonId | FK
username | String

reaction 관계 테이블을 위처럼 만들어서 user테이블과는 관계를 가지지 않도록 해줄 수 있을 것 같은데 어떻게 생각하시나요?

**Comment by sbyeol3** [comment]
찬성입늬다

**Comment by Taeg92** [comment]
### ERD 수정
> [수연님 의견 반영](https://github.com/boostcamp-2020/IssueTracker-10/issues/15#issuecomment-717739755)

![issueTracker-ERD](https://user-images.githubusercontent.com/60081031/97403319-8cbca100-1937-11eb-9005-d7a5dde71d0d.JPG)
