### ISSUE TITLE
[MEET] API 명세서 작성

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#16]
## 장소 및 시간
10.28 수요일 오후 온라인

## 참석자
태경, 수연, 샛별

## 논의 내용
API 명세서 작성 후 위키에 업로드하기
Hack md로 공동작업

**Comment by Park-SooYeon** [comment]
## 좀 더 고민해보면 좋을 내용
* 코멘트 생성 시간을 나타낼 때, 시간차이 계산을 서버단에서 해줄 것인지 프론트에서 해줄 것인지에 대한 이슈
*  api 요청을 보냈을 때, 추가 및 삭제할 데이터가 데이터가 존재하거나 존재하지 않을 경우, 응답 코드를 409로 해줄지 422로 해줄지에 대한 이슈
* 이슈 상세 API에 코멘트 배열을 추가할 것인지? 아니면 이슈정보만 넣고, 코멘트 API는 따로 호출할 것인지?
