### ISSUE TITLE
[BUG] issue status 불일치

### ISSUE THREAD

**Issue by Park-SooYeon** [boostcamp-2020/IssueTracker-10#45]
## 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.
* state가 1(open)인 이슈들이 close된 이슈로 개수가 카운팅되어 반환되는 것 같습니다.

## 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.
* issue의 state가 1이면 open, state가 0이면 close된 issue로 카운팅해야합니다.

## 참고자료
> 보여지는 뷰의 경우 스크린샷도 함께 첨부합니다.
![image](https://user-images.githubusercontent.com/49746644/97650084-43399680-1a9c-11eb-89e8-ca6406f8f819.png)
![image](https://user-images.githubusercontent.com/49746644/97650101-4a60a480-1a9c-11eb-9956-b9d76cee2085.png)

**Comment by Taeg92** [comment]
확인했습니다! 수정할게요 :cry:
