### ISSUE TITLE
[Label view] CollectionView + Cell

### ISSUE THREAD

**Issue by hoonv** [boostcamp-2020/IssueTracker-10#7]
## 설명
> 이슈에 대한 설명을 작성합니다. 담당자도 함께 작성하면 좋습니다.

레이블 뷰의 틀만 만든다. (편집뷰 제외)

## 체크사항
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다.

- [ ] 레이블 화면에서는 전체 레이블 목록을 표시한다.
레이블 이름과 배경색을 함께 표시한다.
설명은 레이블 이름 아래 한 줄만 표시한다.

- [ ] [+] 버튼을 누르면 레이블 추가 화면으로 이동한다. 

- [ ] 레이블 셀을 선택하면 편집 화면으로 이동한다.

## 참고자료
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

## 관련 논의
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.

**Comment by kati-kms** [comment]
Comment

**Comment by kati-kms** [comment]
Second
