### ISSUE TITLE
[MEET/REFACTOR] 백엔드 파트 코드 리팩토링

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#70]
## 장소 및 시간
2주차 화요일 오프라인

## 참석자
웹 담당 (태경, 수연, 샛별)

## 논의 내용
1. 서비스 함수 내에서 조회하는 함수의 네이밍 : `select` `get` `find` `read`
2. 해당 데이터가 존재하는지 여부를 모델에서 리턴할 것인지, 서비스에서 리턴할 것인지
3. 성공/에러 메시지가 다수 겹치는 데 어떻게 짜야할지
4. 메시지 포맷이 일정하지 않음

**Comment by Park-SooYeon** [comment]
sequelize에서 raw, plain 옵션을 통일하는 것도 좋을 것 같습니다.

**Comment by sbyeol3** [comment]
5. 모델함수나 서비스 함수들을 비구조화할당으로 빼올지, 객체로 뺄지
