### ISSUE TITLE
[BUG] 존재하지 않는 Issue에 대한 issue detail message

### ISSUE THREAD

**Issue by Taeg92** [boostcamp-2020/IssueTracker-10#75]
## 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.

- [x] issue detail 조회 API에서 issue가 존재 하지 않을 때 server error message를 보내줍니다.

## 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

- issue가 존재하지 않을 때 404 error를 반환 하는 것이 좋지 않을까요?

## 참고자료
> 보여지는 뷰의 경우 스크린샷도 함께 첨부합니다.

**Comment by Park-SooYeon** [comment]
#61 번 이슈에 남겨둔 버그입니다!
지금바로 수정해서 PR 보내겠습니다:)
