### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by Park-SooYeon** [boostcamp-2020/IssueTracker-10#8]
## 설명
> 이슈에 대한 설명을 작성합니다. 담당자도 함께 작성하면 좋습니다.

오프라인 미팅 중 DB 설계 후, ERD를 그려서 readme에 ERD 구조를 이미지로 추가합니다.

## 체크사항
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다.
- [x] DB 설계 후, ERD 그리기
- [x] README에 ERD 구조 이미지 추가

## 참고자료
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

## 관련 논의
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.

**Comment by sbyeol3** [comment]
![image](https://user-images.githubusercontent.com/43198553/97247081-45081d80-1842-11eb-993b-e9b519ed4a39.png)

**Comment by Taeg92** [comment]
## ERD 수정

![issueTracker_ERD](https://user-images.githubusercontent.com/60081031/97257007-fc5b5f00-1857-11eb-9d9e-6c75678a107b.PNG)

### 수정 이유

- issue content가 존재하지 않기 때문에 삭제
- comment에 issue foreign key가 빠져 있어서 추가

**Comment by Taeg92** [comment]
### ERD 수정
![issueTracker-ERD](https://user-images.githubusercontent.com/60081031/97398111-f932a280-192d-11eb-8812-f3299218ffe1.JPG)

### 수정 이유
- milestone column에 state빠져서 추가하였습니다.

**Comment by Taeg92** [comment]
### ERD 최종 수정

![issueTracker_ERD](https://user-images.githubusercontent.com/60081031/97946876-f7099180-1dce-11eb-8e95-198a975ba1a9.PNG)

### 수정 이유

- userId FK 사용하지 않고 username만 저장
- comment에 issueId 추가
