### ISSUE TITLE
[REFACTOR] 백엔드 리팩토링

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#87]
## 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.

## 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

웹 백엔드 리팩토링할 부분 있으면 코멘트에 추가하기

## 참고자료
> 보여지는 뷰의 경우 스크린샷도 함께 첨부합니다.

**Comment by Park-SooYeon** [comment]
sequelize에서 raw, plain 옵션을 하나로 통일하는게 좋을 것 같아요.
