### ISSUE TITLE
[MEET] 1차 오프라인 미팅

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#9]
## 장소 및 시간

일시 : 2020.10.27 화요일 오전 10시
장소 : 왕십리역 스터디룸

## 참석자
`전원 참석!`

## 논의할 내용
- 아이스 브레이킹
- 서버 개발환경 구축
- ERD 작성
- 리드미 작성
- 대략적인 API 명세서 작성하기 `굿 아이디어 수연님~`

## 논의한 내용 정리
> 위키 페이지에 정리하고 위키 링크 연결

**Comment by sbyeol3** [comment]
전원 참석~

**Comment by kati-kms** [comment]
우리 이슈트래커를 대표하는 색상을 정해봤으면 좋겠습니다.

**Comment by sbyeol3** [comment]
저는 주황색이나 보라색 추천합니다. @kati-kms

**Comment by sbyeol3** [comment]
<img width="882" alt="스크린샷 2020-10-27 오후 6 05 21" src="https://user-images.githubusercontent.com/43198553/97279969-fc228a00-187e-11eb-96b7-bc27e6670c36.png">
